// <auto-generated />
namespace CompareCloudware.POCOQueryRepository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_AdvertisingImageServer_IsServing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_AdvertisingImageServer_IsServing));
        
        string IMigrationMetadata.Id
        {
            get { return "201311171819012_Add_AdvertisingImageServer_IsServing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
