// <auto-generated />
namespace CompareCloudware.POCOQueryRepository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SiteAnalytic_RemoveDateStampsAndRowVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SiteAnalytic_RemoveDateStampsAndRowVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "201307171358194_SiteAnalytic_RemoveDateStampsAndRowVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
