// <auto-generated />
namespace CompareCloudware.POCOQueryRepository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddContentText_LineBreakBeforeAfter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddContentText_LineBreakBeforeAfter));
        
        string IMigrationMetadata.Id
        {
            get { return "201408102137385_AddContentText_LineBreakBeforeAfter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
